import React from 'react'
import { NavLink,Outlet } from 'react-router-dom'
function Products() {
  
  return (
    <div>
    <input type="text" placeholder='Search'/>
 <nav>
  <NavLink to="Top">Top</NavLink>
  <NavLink to= "Latest">Latest</NavLink>
 </nav>
   <Outlet/>


   <div>
    Lorem Ipsum
"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vel ante mattis, luctus mi ac, molestie augue. Vestibulum sagittis ipsum justo, id lacinia turpis rutrum vel. Integer tortor metus, porta id eros sed, blandit maximus purus. In iaculis ullamcorper dapibus. Maecenas fringilla massa sodales nulla luctus, tempus ornare risus dapibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer ut consectetur erat. Aliquam facilisis diam nibh, a feugiat neque porttitor sit amet.

Cras ut neque consectetur, rutrum felis et, tempor odio. Donec rutrum turpis ut sapien porttitor, vel hendrerit diam auctor. Pellentesque mattis tristique porttitor. Nulla facilisi. Duis pulvinar mi a nisl facilisis, et tempor lacus varius. Vivamus egestas sed libero eu vestibulum. Mauris pharetra a eros vel vehicula.

Donec ut libero id massa fermentum rhoncus. Ut eleifend massa in efficitur viverra. Etiam metus sapien, ultrices ut elementum sed, lacinia eget massa. Ut venenatis ex enim, vel porta tortor tincidunt in. Aenean dapibus purus sit amet nisl bibendum, et faucibus massa sollicitudin. Phasellus quis ante at orci faucibus dignissim. Morbi iaculis ex nibh, ut interdum turpis posuere sed. Etiam consectetur luctus nibh nec ultricies. Nulla id nisi magna. Suspendisse tristique risus lacus, ut pellentesque elit rhoncus ac. Sed efficitur nibh erat, ut laoreet massa posuere a. Aenean at augue in nulla pretium ultrices. Pellentesque pulvinar sed ante sed viverra. Aliquam vel iaculis diam, at facilisis tellus.

Integer dui dui, volutpat sed diam non, sollicitudin convallis tortor. In quis turpis dapibus, porttitor diam non, tristique arcu. Donec lacinia vulputate ligula ut efficitur. Suspendisse ornare, diam pretium pulvinar consectetur, justo eros fermentum nisl, a finibus turpis nisl imperdiet nibh. Vestibulum orci sapien, euismod quis elit ullamcorper, molestie suscipit lorem. Sed feugiat dui ac fermentum vulputate. Nullam vehicula porta felis ac tempor. Curabitur sodales sed sem cursus scelerisque. Nullam condimentum nulla gravida neque lacinia gravida et eget quam. Proin pulvinar mauris velit, eget dapibus ex posuere in. Pellentesque eu metus vitae augue sodales tincidunt in at justo. Cras tincidunt leo eu lectus ullamcorper, et consectetur augue tincidunt. Quisque consectetur a magna a aliquam. Vestibulum dignissim pulvinar dictum. Nullam est sem, tristique quis libero vitae, tempus malesuada nunc.

Nam lobortis ligula vel tellus euismod consectetur. In lacus magna, fermentum quis scelerisque nec, gravida sit amet justo. Fusce a fringilla tortor, eget hendrerit urna. Morbi viverra pretium molestie. Ut pulvinar facilisis ipsum ut pretium. Donec tempor rutrum imperdiet. Donec leo ante, suscipit ac consequat eget, iaculis id tortor. Fusce viverra odio id nunc ultricies, sit amet congue massa posuere. Ut venenatis volutpat ultricies. Mauris sed elit eget tellus suscipit sollicitudin id quis orci. Nulla ipsum enim, molestie eu mauris sed, dictum sollicitudin elit. Sed tristique accumsan augue, id laoreet est molestie non. Vivamus fringilla viverra risus ac imperdiet.

Duis posuere consectetur diam ut pharetra. Cras ac ante et lorem gravida ultrices. Morbi tempor, libero in tincidunt sollicitudin, lorem metus fringilla orci, ac pharetra orci orci sit amet urna. Suspendisse eget massa lacus. Curabitur egestas, ex eget condimentum varius, sapien justo aliquet libero, sodales varius leo ante vel dolor. Suspendisse ipsum leo, rutrum sed condimentum eget, sagittis sit amet metus. Morbi iaculis tortor et mauris mattis congue. Donec convallis nec tellus ut euismod. Praesent orci quam, viverra nec consequat sit amet, tincidunt at orci. Mauris eleifend lorem a facilisis mollis. Suspendisse iaculis dapibus turpis at rhoncus. Maecenas aliquet varius vestibulum. Cras gravida ex quis dui ultrices volutpat. Aliquam ac pellentesque mi. Aliquam volutpat erat sed turpis sollicitudin blandit. Nulla vestibulum risus sit amet neque bibendum, imperdiet semper leo imperdiet.

Etiam consequat libero fermentum consectetur tristique. Sed nec ullamcorper nisl, vel vulputate metus. Fusce vitae feugiat enim. Maecenas dolor turpis, aliquam et viverra vehicula, semper ac dolor. Donec malesuada gravida diam. Sed at leo at dui aliquet laoreet nec in purus. Nam vitae mauris ante. Praesent sapien justo, feugiat sagittis felis rutrum, semper varius magna. Sed quis ex eget ipsum sodales convallis. Vestibulum at metus vel justo convallis ultricies sed quis metus. Donec porttitor commodo sapien, hendrerit volutpat lectus ullamcorper id. Nunc leo metus, sodales ac ipsum sit amet, semper lobortis nisl. Morbi dapibus dolor at viverra interdum.

Maecenas sem libero, consectetur sit amet urna sit amet, tristique iaculis dui. Etiam a augue massa. Nam sodales sapien tortor, quis accumsan metus sollicitudin nec. In elementum, metus sit amet pretium lobortis, metus velit elementum sem, commodo pulvinar ipsum eros quis lorem. Duis ac accumsan diam. Proin neque lorem, ornare nec varius et, scelerisque vitae nibh. Donec vulputate, leo eleifend auctor rutrum, dui purus accumsan dui, nec fermentum enim est a orci.

Praesent tortor augue, consectetur eget fermentum sit amet, dictum vulputate arcu. Proin tincidunt arcu ipsum, nec maximus est tincidunt eget. Integer ultricies ipsum et tempor pharetra. In laoreet ultricies vehicula. Nulla ac urna metus. Nunc sem eros, congue a fermentum sed, suscipit vel dolor. Fusce vel diam sollicitudin, ullamcorper nisl non, mollis lorem. Vivamus feugiat ligula et tellus posuere aliquam. Nunc tincidunt orci vitae lacus sodales, quis porttitor nisi imperdiet. Phasellus laoreet tellus diam, dictum dictum magna pellentesque quis. Nunc posuere lobortis dui, maximus aliquam odio sagittis nec.

Vivamus in lorem purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam suscipit leo nec neque mollis ultrices. Praesent luctus ante eu nisi fringilla finibus. Donec nec mi id massa commodo viverra. Duis facilisis nunc sit amet vestibulum porta. Fusce cursus sagittis accumsan. Phasellus porta fringilla sapien ac eleifend. Fusce sagittis nisi sem, a interdum nunc bibendum nec. Pellentesque lacinia, elit vitae bibendum iaculis, sem neque viverra massa, at hendrerit purus nibh quis dui.   
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut aliquam massa ultrices risus sodales porttitor. Pellentesque ultrices arcu consequat cursus condimentum. Pellentesque nec imperdiet libero. Fusce a arcu tincidunt ex blandit feugiat sed non augue. Phasellus rhoncus turpis mi, nec semper ligula consequat quis. Vivamus dolor urna, hendrerit non neque et, cursus hendrerit tortor. Donec porttitor mauris in egestas tempus. Mauris mollis urna ut nisl luctus porta. Nunc sapien leo, malesuada in erat quis, varius malesuada dolor. Sed faucibus pulvinar imperdiet. Maecenas nunc felis, sagittis vestibulum elementum quis, dictum id erat. Sed ut semper libero. Suspendisse at suscipit lacus. Pellentesque ultricies aliquam turpis sed vestibulum.

Sed diam felis, vehicula et diam in, condimentum cursus libero. Suspendisse condimentum blandit lectus, sed eleifend nibh molestie vel. Mauris tincidunt egestas enim, malesuada venenatis tellus ultrices vehicula. Curabitur in tincidunt diam. Aliquam rutrum nunc non sem tempus ullamcorper. Cras molestie erat in lectus sagittis fermentum. Ut turpis purus, lacinia non tristique nec, auctor tristique orci. Maecenas viverra lobortis metus eu dignissim.

Mauris nibh erat, faucibus ut malesuada in, elementum non diam. Sed vehicula luctus gravida. Ut condimentum imperdiet vehicula. Ut tincidunt consequat sem id interdum. Donec pretium massa ac laoreet tincidunt. Quisque tempus orci id fermentum euismod. Nunc pharetra scelerisque libero, et bibendum massa sollicitudin id. Morbi dolor metus, hendrerit ac purus eu, consequat egestas diam. Nam dapibus purus sed ligula tincidunt interdum.

Nulla rhoncus metus et enim faucibus, dapibus luctus leo tempus. Etiam pellentesque dui eu nunc tristique mollis. Sed rhoncus lacinia faucibus. Proin convallis, erat at ultrices placerat, magna dolor commodo augue, at blandit diam tellus in nisi. Maecenas eget purus nec felis faucibus vehicula non vel eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer elementum tristique porttitor. Duis odio quam, convallis at ligula non, sodales semper quam. Sed ultrices diam et ex tempor, non porttitor massa fermentum. Quisque ut quam congue, elementum massa non, ultricies nisl. Integer nibh neque, suscipit eget urna ac, maximus venenatis turpis. Praesent congue est sapien. Aliquam erat volutpat. Nam porttitor tincidunt varius. Proin consequat nibh ac nunc tincidunt, a maximus massa facilisis.

Cras vitae nulla gravida orci faucibus dignissim. Mauris sollicitudin, turpis id pharetra rutrum, lacus lacus dictum ex, quis feugiat nibh sapien vel enim. Morbi sit amet nisl ipsum. Cras dignissim, lorem sed ornare faucibus, enim sem pellentesque tellus, eget facilisis tellus metus vitae odio. Nam vel tellus dignissim urna mattis convallis. Ut at quam vitae nulla ultrices semper bibendum ac metus. Nullam semper fermentum mauris, vel sodales turpis tristique vitae. Etiam erat sapien, dignissim a placerat at, feugiat vitae felis. Nullam vel odio lacinia, sodales turpis vel, feugiat elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque lobortis, dolor a bibendum consequat, justo tortor porta lectus, et venenatis tellus magna a tellus. Quisque finibus urna sit amet ipsum blandit facilisis. In mauris odio, finibus sit amet magna vel, dictum iaculis diam. Nam hendrerit non velit et fringilla. Nam magna arcu, porttitor vel diam et, efficitur gravida ante. Nullam congue nibh nec velit vehicula consequat.

Sed et turpis sapien. Nunc mollis lacus scelerisque feugiat viverra. Proin hendrerit nunc vel mauris iaculis varius nec non urna. Nulla id malesuada ligula, et pharetra eros. Ut ut massa scelerisque, tincidunt orci vel, malesuada erat. Nulla id luctus nisl. In sodales justo diam, et suscipit felis suscipit id. Fusce posuere ornare neque at mattis. Quisque dictum ac tortor quis tempor. Ut non pulvinar eros.

Suspendisse id lobortis sem. Donec porttitor nibh nec arcu pellentesque pulvinar at ut arcu. Curabitur dapibus est ut dui fringilla, eu commodo urna tincidunt. Vivamus mollis non felis fermentum luctus. Cras in felis eu dui faucibus faucibus. Duis viverra justo a ornare efficitur. Maecenas consectetur finibus tellus. Quisque eu eros sit amet est luctus congue. Nam molestie non eros sit amet iaculis. In in tortor condimentum, feugiat nunc ut, egestas tortor.

Sed mollis enim porta ultrices consequat. Fusce pretium ex et urna pharetra, et malesuada odio feugiat. Nunc ac neque est. Quisque dapibus sapien sed consequat iaculis. Aliquam erat volutpat. Donec eget nunc congue, iaculis eros ut, congue felis. Cras tristique consectetur arcu a varius. Cras nec velit mi. Integer vitae libero id ipsum bibendum tincidunt.

Ut sit amet rhoncus eros. Phasellus massa ex, finibus id lorem tempus, consectetur tincidunt nulla. Phasellus fringilla luctus turpis vitae tristique. Nunc a tempor eros. Nulla vitae tincidunt enim. Nulla non placerat orci, eget tincidunt neque. In nec est vestibulum, semper leo nec, ultrices nibh. Suspendisse vitae purus urna. Nam id lacus sem. Nulla facilisi. Aliquam ut placerat arcu. Nam consectetur iaculis massa et imperdiet. Proin eu rhoncus felis, at rhoncus tortor.

Quisque ultrices turpis nec risus commodo dictum. Integer eget justo sit amet arcu fringilla molestie eu vel neque. Integer lobortis augue a lectus mollis, at volutpat ligula hendrerit. Donec vel sem at dui aliquam consequat sit amet quis felis. Mauris nec elit ac arcu dapibus dignissim. Aliquam vulputate cursus erat vel sagittis. Morbi vel erat sem. Nunc eget aliquam diam. Praesent a neque justo. Aliquam erat nibh, euismod at aliquet vel, pulvinar id sapien. Phasellus ornare, justo porta imperdiet pharetra, orci lorem faucibus felis, at consectetur lectus dolor eu diam.

Donec venenatis ultrices molestie. Nunc iaculis nunc non magna molestie condimentum. Vestibulum laoreet eros eu leo ornare, nec tempus mi pellentesque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in hendrerit diam, in scelerisque sem. Morbi non magna et magna condimentum efficitur non in nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut ornare velit eget lacus volutpat, et dignissim mauris consectetur. Praesent faucibus, libero vitae maximus tincidunt, urna tellus convallis odio, ut lacinia velit elit in tortor. Etiam sed aliquam ipsum, id efficitur neque. Proin dignissim at nisi sit amet mollis. Nam suscipit quam magna, at lobortis ante mollis eu. Vestibulum maximus vestibulum odio in pellentesque. Mauris iaculis erat quis diam blandit feugiat. Quisque at velit lobortis, varius tortor in, tempor massa.

Duis tempor malesuada tellus, at dapibus elit rhoncus non. Integer pretium interdum ante id vehicula. Phasellus sit amet posuere lectus. Etiam pretium, sapien non malesuada venenatis, massa massa blandit eros, eu convallis nibh odio ac eros. Nullam non tincidunt lacus, eu ultricies orci. Aliquam sodales placerat dolor, a dictum massa condimentum non. Phasellus dignissim vel enim in iaculis. Pellentesque nulla quam, pellentesque in dignissim pharetra, lobortis quis ligula. Nullam vestibulum, arcu vel vulputate viverra, augue mi iaculis mauris, vel condimentum risus orci id ligula.

Etiam in tempor dui, eu vulputate dolor. Suspendisse pulvinar ipsum ante, eu hendrerit nulla convallis vel. Maecenas eu aliquam turpis, imperdiet sollicitudin libero. Duis vel imperdiet nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed bibendum ipsum nulla, at maximus quam blandit ut. Ut vel nisl felis. Aliquam volutpat gravida ipsum ut aliquam. Etiam sollicitudin enim at felis varius, consectetur consequat arcu tincidunt. Nam risus risus, scelerisque quis ullamcorper nec, interdum et enim. Maecenas pretium faucibus nisi eget sodales.

Praesent eu lacinia enim. In eleifend, elit non efficitur tempor, metus ex tincidunt justo, nec suscipit nulla lacus non quam. Donec quam purus, suscipit vel massa et, tempus sodales arcu. Donec eget finibus eros. Vestibulum maximus consequat lectus id cursus. Fusce elementum ultricies ex, ut suscipit nisi rhoncus vitae. Sed ac sapien nec odio egestas viverra in a massa. Maecenas ornare, lorem ut congue gravida, tortor est vulputate sem, vel placerat turpis mauris vel erat.

Aenean viverra turpis eget hendrerit euismod. Duis porta, nunc sit amet eleifend tempor, arcu diam tincidunt est, posuere eleifend justo est id justo. Aliquam in dui tortor. Morbi fermentum a dolor non ullamcorper. Nunc tempor eros luctus blandit condimentum. Sed fringilla nulla sed nunc sollicitudin, nec iaculis ex efficitur. Integer molestie, felis sit amet posuere tempus, neque quam lacinia urna, in malesuada sem velit sed elit. In rhoncus, mauris et mollis commodo, justo turpis vulputate nisl, ut dapibus orci ligula non turpis. Maecenas pharetra a nisi sit amet convallis. Aenean ut neque eget lorem semper placerat. Nulla in dolor ac mauris tincidunt tristique.

Sed tempor arcu sed congue feugiat. Etiam non turpis sit amet justo volutpat imperdiet vitae nec quam. Fusce hendrerit molestie velit quis cursus. Nunc quis varius mauris, eget porta urna. Vestibulum magna neque, gravida facilisis malesuada sed, finibus id enim. In semper risus a justo accumsan gravida. Nam volutpat elit id volutpat placerat. Quisque tincidunt ex elit, et auctor nisl tincidunt vitae. Suspendisse pretium felis id ex varius feugiat a sit amet ligula. Sed finibus lorem purus, vel placerat velit imperdiet a. Nullam eget fringilla odio.

Quisque mauris lacus, dapibus in lacus quis, semper pellentesque neque. Ut pulvinar erat vitae purus lacinia, a semper urna scelerisque. Ut elementum leo purus, vel egestas velit blandit et. Nullam in est iaculis, sodales justo eget, suscipit sem. Sed consectetur, tellus nec scelerisque sodales, magna ante commodo augue, eu molestie nisi purus eget felis. Vivamus cursus lacus vel est ullamcorper, sit amet facilisis leo malesuada. Ut ante velit, congue at facilisis interdum, gravida sed lectus. Fusce bibendum rhoncus fringilla.

Fusce lorem arcu, posuere fermentum tristique eget, elementum quis enim. Nam consectetur lorem eget consequat rhoncus. Pellentesque finibus condimentum tristique. Proin semper maximus vehicula. Phasellus in tellus eget odio luctus finibus et sed lacus. Pellentesque a eros aliquam, tempus nulla pharetra, iaculis erat. Donec quis dui ullamcorper, lacinia metus et, suscipit eros. Proin malesuada orci justo, ac sollicitudin dui consectetur ac. Proin dictum pellentesque neque volutpat laoreet. Aliquam at ultrices velit. Cras tincidunt enim nec tempor finibus. Phasellus non lectus risus. Suspendisse mattis vulputate arcu, gravida posuere lacus posuere vitae. Donec vehicula ipsum in congue finibus. Fusce facilisis leo eget elit consequat, ut sollicitudin mi finibus.

Cras in erat eu turpis luctus sagittis non sed ligula. Nullam eget ornare ligula. Sed ac turpis nec purus porttitor suscipit eget vel justo. Aliquam at neque ullamcorper, mollis lectus non, pellentesque nisl. Vivamus tincidunt laoreet mauris id fringilla. Nam at justo vel lacus laoreet scelerisque. Vestibulum ullamcorper purus facilisis volutpat posuere. Curabitur non pretium urna, et placerat dolor. Cras in tristique neque, ut mattis nisi.

Praesent lacinia magna eros, a finibus eros interdum sit amet. Donec convallis, nulla quis sodales gravida, dolor nunc tempus augue, sit amet hendrerit dolor ante a est. Donec vitae pretium velit. In luctus consectetur lectus et imperdiet. Ut sit amet tincidunt arcu. Etiam aliquam velit dignissim libero varius, et fringilla urna sodales. Mauris sit amet ipsum imperdiet, mattis lorem sit amet, aliquam dolor.

Generated 20 paragraphs, 1738 words, 11703 bytes of Lorem Ipsum
   </div>
    </div>
  )
}

export default Products
